logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
spring:
  data:
    mongodb:
      database: test
      port: 50060
  profiles:
    active: local
  main:
    web-application-type: none

app:
  constants:
    awsMailContentCharset: UTF-8
    awsMessageIdKeyName: awsMessageId
    tempFileDir: /Users/itaesu/Desktop/Work/deploy/temp

  maxProcessCapacity: 10